#! /usr/bin/python
# -*- coding: utf-8 -*-
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

import time

def isPantagonal(number):
	tmp = ((24 * number + 1) ** .5 + 1) / 6
	return tmp == int(tmp)

def isHexagonal(number):
	tmp = ((8 * number + 1) ** .5 + 1) / 4
	return tmp == int(tmp)

def solution():
	n, triangle = 286, 40755
	while True:
		triangle += n
		n += 1
		if isPantagonal(triangle) and isHexagonal(triangle):
			break
	print 'The answer is {}' .format(triangle)

def main():
	start = time.clock()
	solution()
	print 'Elapsed: {} ms' .format(1000 * (time.clock() - start))


if __name__ == '__main__':
	main()
