#! /usr/bin/python
# -*- coding: utf-8 -*-
'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
'''

import time

def dictAppend(nDict, n):
    if nDict.has_key(n):
        nDict[n] += 1
    else:
        nDict[n] = 1
    return

def numOfDivisors(n):
    divisorNum = 1
    divisor = 2
    nDict = dict()
    if n == 0 or n == 1:
        return None
    while n != 1:
        if n % divisor == 0:
            dictAppend(nDict, divisor)
            n = n / divisor
        else:
            divisor = divisor + 1
    for item in nDict.items():
        divisorNum *= (item[1] + 1)
    return divisorNum
	
def solution():
    triNum = 0
    n = 1
    while numOfDivisors(triNum) < 500:
        triNum = triNum + n
        n = n + 1
    print 'The answer is {}' .format(triNum)
    return

def main():
    start = time.clock()
    solution()
    print 'Elapsed: {} ms' .format(1000 * (time.clock() - start))
    return


if __name__ == '__main__':
    main()

