# -*- coding: utf-8 -*-
'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def main():
    Hn, Pn, Tn = 0, 0, 0
    nh, np, nt = 143, 165, 286
    while 1:
        Hn = nh * (2 * nh - 1)
        nh += 1
        while Pn < Hn:
            Pn = np * (3 * np - 1) / 2
            np += 1
            if Pn == Hn:
                while Tn < Pn:
                    Tn = nt * (nt + 1) / 2
                    nt += 1
                    if Tn == Pn:
                        return Tn
                        


if __name__ == '__main__':
    print main()